# <div align="center"> Первая часть, до консультации

In [4]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

data = pd.read_csv('data_clean_market.csv', sep=";", encoding='cp1251') # open raw data file

In [5]:
data

,Unnamed: 0,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,0,01.05.2017 0:03,03.05.2017 0:00,4513479_TR,Доставлен,761,761,Магазины,Безналичная,Москва,...,49,2,1,30.04.2017 0:00,55574954-50515053535277,107117_ku13@mail.ru,Марина,ID10020734553,0,NaN
1,18,01.05.2017 2:09,03.05.2017 0:00,4513502_TR,Доставлен,3 299,3 234,Магазины,Безналичная,Красногорск (Красногорский район),...,349,1,1,01.05.2017 0:00,55574954-56545048505170,109109_mm26@gmail.com,Марина,ID59320856,0,NaN
2,31,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7 910,Магазины,Безналичная,Челябинск,...,0,1,1,30.04.2017 0:00,55575349-49505555535574,97117_au24@mail.ru,Анна,ID9010025983048,0,NaN
3,32,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7 910,Магазины,Безналичная,Челябинск,...,0,2,1,30.04.2017 0:00,55575349-49505555535574,97117_au24@mail.ru,Анна,IDL00000795856,0,NaN
4,36,01.05.2017 2:09,10.05.2017 0:00,4513553_TR,Доставлен,2 622,2 622,Магазины,Безналичная,Калуга,...,0,4,1,01.05.2017 0:00,55575351-51495656575170,105117_iu18@yandex.ru,Гость,IDL00000998654,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239260,730549,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3 416,Магазины,Безналичная,Москва,...,49,7,2,30.06.2017 0:00,55574857-57485151544876,107117_ku13@mail.ru,Наталия,IDL00017315250,0,NaN
239261,730550,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3 416,Магазины,Безналичная,Москва,...,49,8,7,30.06.2017 0:00,55574857-57485151544876,107117_ku13@mail.ru,Наталия,IDL00007784452,0,NaN
239262,730551,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3 416,Магазины,Безналичная,Москва,...,49,6,2,30.06.2017 0:00,55574857-57485151544876,107117_ku13@mail.ru,Наталия,IDL00017315452,0,NaN
239263,730556,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2 819,Магазины,Безналичная,Нижний Новгород,...,99,2,4,30.06.2017 0:00,55575450-53495456535575,121109_ym20@gmail.com,Мария,ID000sm-0652654,0,NaN
239264,730557,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2 819,Магазины,Безналичная,Нижний Новгород,...,99,3,2,30.06.2017 0:00,55575450-53495456535575,121109_ym20@gmail.com,Мария,ID000sm-0652452,0,NaN

**Посмотрим содержимое группы 2 и их количество, позже мы их будем использовать в качестве названий колонок витрины для market basket**

In [5]:
cols = np.unique(data["Группа2"].values)
print(cols)

['ДЕТСКОЕ ПИТАНИЕ' 'ЖЕНСКИЕ ШТУЧКИ' 'ИГРУШКИ' 'КАНЦТОВАРЫ, КНИГИ, ДИСКИ'
 'КОСМЕТИКА/ГИГИЕНА' 'КРУПНОГАБАРИТНЫЙ ТОВАР' 'ОБУВЬ' 'ПОДГУЗНИКИ'
 'СОПУТСТВУЮЩИЕ ТОВАРЫ' 'ТЕКСТИЛЬ, ТРИКОТАЖ' 'ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА'
 'ТОВАРЫ ДЛЯ ЖИВОТНЫХ' 'ТОВАРЫ ДЛЯ КОРМЛЕНИЯ']

In [79]:
data["Группа2"].value_counts()

ИГРУШКИ                      50691
ТЕКСТИЛЬ, ТРИКОТАЖ           43573
ДЕТСКОЕ ПИТАНИЕ              37092
ПОДГУЗНИКИ                   28879
КОСМЕТИКА/ГИГИЕНА            23938
КРУПНОГАБАРИТНЫЙ ТОВАР       18008
ТОВАРЫ ДЛЯ КОРМЛЕНИЯ         16195
КАНЦТОВАРЫ, КНИГИ, ДИСКИ      9280
ОБУВЬ                         6821
ТОВАРЫ ДЛЯ ЖИВОТНЫХ           3646
СОПУТСТВУЮЩИЕ ТОВАРЫ           596
ЖЕНСКИЕ ШТУЧКИ                 459
ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА       87
Name: Группа2, dtype: int64

**Посмотрим теперь чеки, соберём из них словарь для индексов**

In [107]:
data["НомерЗаказаНаСайте"].value_counts()

5029815_TR       120
4998002_TR       102
4850758_TR       101
4738803_TR        86
4990180_TR        81
                ...
4826212_TR         1
4535127_TR         1
4735480_TR         1
2009000664_TR      1
4577650_TR         1
Name: НомерЗаказаНаСайте, Length: 77708, dtype: int64

In [108]:
checks = np.array(data["НомерЗаказаНаСайте"])
checks = np.unique(checks)
print(len(checks))
print(checks)

77708
['1303000353_TR' '1303000358_TR' '1303000359_TR' ... '5031782_TR'
 '5031783_TR' '5031784_TR']

In [109]:
checks_loc = {key: i for i, key in enumerate(checks)}

**Создадим витрину с теми колонками, начнём заполнять**

In [110]:
mba = pd.DataFrame(columns=cols)

In [111]:
#Функция для добавления новой строки в таблицу, которая заполнена нулями
def add_row(df):
    temp = pd.DataFrame(0, index=[i for i in checks], columns=cols)
    df = df.append(temp, ignore_index=False, sort=False)
    return df

In [112]:
mba = add_row(mba)
mba = mba.reset_index()
mba = mba.rename(columns={"index": "ЧЕК"})
mba

,ЧЕК,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,1303000353_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1303000358_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1303000359_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1303000360_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1303000362_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77703,5031766_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
77704,5031767_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
77705,5031782_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
77706,5031783_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
77707,5031784_TR,0,0,0,0,0,0,0,0,0,0,0,0,0

**Теперь будем добавлять товары**

In [113]:
#Идём по строкам таблицы, добавляем количество товара в чек
for i in range(0, 239265):
    check = data["НомерЗаказаНаСайте"][i]
    j = checks_loc[check]
    mba[data["Группа2"][i]][j] = mba[data["Группа2"][i]][j] + data["КоличествоПроданоКлиенту"][i]

In [114]:
mba

,ЧЕК,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,1303000353_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
1,1303000358_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
2,1303000359_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
3,1303000360_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
4,1303000362_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77703,5031766_TR,0,0,0,0,0,0,0,0,0,0,0,45,0
77704,5031767_TR,0,0,1,0,0,0,0,0,0,0,0,0,0
77705,5031782_TR,0,0,2,0,1,0,0,0,0,13,0,0,1
77706,5031783_TR,6,0,0,0,0,0,0,2,0,0,0,0,0
77707,5031784_TR,0,0,1,0,0,0,0,0,0,3,0,0,0

**Сохраним её, если нужно**

In [115]:
mba.to_csv('market_basket.csv', sep=";", encoding='cp1251') #save filtered dataframe

**Теперь создадим новую таблицу для показателей, потом будем её заполнять**

Откроем файлы (они предварительно сохранены), чтобы не пересчитывать всё заново. А также создадим все возможные пары из названий категорий, запишем их в список rows.

In [119]:
import itertools

data = pd.read_csv('data_clean_market.csv', sep=";", encoding='cp1251') # open raw data file
mba = pd.read_csv('market_basket.csv', sep=";", encoding='cp1251') # open raw data file

In [120]:
params = ["support", "confidence", "lift", "expected confidence"]
res = pd.DataFrame(columns=params)

In [121]:
rows = [' + '.join(i) for i in itertools.permutations(cols, 2)] #Список для названий строк
pairs = list(itertools.permutations(cols, 2)) #Список, с которым легко работать, чтобы считать показатели
print("Так выглядит список кобминаций, их " + str(len(rows)) + ", ниже приведён пример:\n")
print(rows[1:5])

Так выглядит список кобминаций, их 156, ниже приведён пример:

['ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ', 'ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ', 'ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА', 'ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР']

In [122]:
temp = pd.DataFrame(0, index=[i for i in rows], columns=params)
res = res.append(temp, ignore_index=False, sort=False)
res = res.reset_index()
res = res.rename(columns={"index": "Пара"})
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0,0,0,0
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0,0,0,0
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0,0,0,0
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0,0,0,0
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0,0,0,0
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0,0,0,0
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0,0,0,0
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0,0,0,0
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0,0,0,0
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0,0,0,0

**Создадим функции для рассчёта показателей**

1. Support
2. Confidence
3. Expected confidence
4. Lift - данный показатель можно выразить через 2 другие функции, но для экономии вычислительного времени просто будем использовать полученные результаты и деление.

In [123]:
def support(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[a][i] > 0 and df[b][i] > 0:
            counter += 1
    return counter/len(df)

In [124]:
def confidence(a, b, df):
    counter = 0
    total = 0
    for i in range(0, len(df)):
        if df[a][i] > 0:
            total += 1
            if df[b][i] > 0:
                counter += 1
    return counter/total

In [125]:
def expconf(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[b][i] > 0:
            counter += 1
    return counter/len(df)

**Теперь заполним итоговую таблицу**

In [127]:
for i in range(0, len(pairs)):
    sup = support(pairs[i][0], pairs[i][1], mba)
    conf = confidence(pairs[i][0], pairs[i][1], mba)
    exconf = expconf(pairs[i][0], pairs[i][1], mba)
    lift = (conf / exconf)
    res['support'][i] = sup
    res['confidence'][i] = conf
    res['expected confidence'][i] = exconf
    res['lift'][i] = lift

In [128]:
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0.000463273,0.00378668,1.55691,0.00243218
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0.0196891,0.160934,0.526784,0.305503
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.0048515,0.039655,0.949618,0.0417589
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0.0248366,0.203008,1.77052,0.11466
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.00611263,0.0499632,0.25651,0.19478
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0.0370618,0.329784,1.27155,0.259356
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0.000347455,0.00309172,0.698405,0.00442683
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0.021851,0.194435,1.00567,0.193339
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0.000205899,0.00183213,2.73791,0.000669172
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0.0010681,0.00950418,0.535958,0.0177331

**Сохраним полученную таблицу**

In [129]:
res.to_csv('mba_result.csv', sep=";", encoding='cp1251') #save filtered dataframe

**Поставим ограничения по support и confidence**

In [18]:
res = pd.read_csv('mba_result.csv', sep=";", encoding='cp1251') # open raw data file
del res["Unnamed: 0"]
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0.000463,0.003787,1.556908,0.002432
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0.019689,0.160934,0.526784,0.305503
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.004851,0.039655,0.949618,0.041759
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0.024837,0.203008,1.770524,0.114660
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.006113,0.049963,0.256510,0.194780
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0.037062,0.329784,1.271550,0.259356
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0.000347,0.003092,0.698405,0.004427
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0.021851,0.194435,1.005667,0.193339
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0.000206,0.001832,2.737908,0.000669
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0.001068,0.009504,0.535958,0.017733

*Переведём значения в проценты*

In [21]:
for i in range(0, len(res)):
    res["support"][i] *= 100
    res["confidence"][i] *= 100
    res["expected confidence"][i] *= 100

In [23]:
res.columns = ['Пара', 'support(%)', 'confidence(%)', 'lift', 'expected confidence(%)']
res

,Пара,support(%),confidence(%),lift,expected confidence(%)
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0.046327,0.378668,1.556908,0.243218
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,1.968909,16.093405,0.526784,30.550265
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.485150,3.965499,0.949618,4.175889
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,2.483657,20.300831,1.770524,11.466001
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.611263,4.996319,0.256510,19.478046
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,3.706182,32.978358,1.271550,25.935554
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0.034745,0.309172,0.698405,0.442683
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",2.185103,19.443490,1.005667,19.333917
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0.020590,0.183213,2.737908,0.066917
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0.106810,0.950418,0.535958,1.773305

**Только 2 строки, где поддержка больше 5%**

In [25]:
res_1 = res[res["support(%)"] >= 5]
res_1

,Пара,support(%),confidence(%),lift,expected confidence(%)
54,КОСМЕТИКА/ГИГИЕНА + ПОДГУЗНИКИ,5.62233,49.034792,1.89064,25.935554
88,ПОДГУЗНИКИ + КОСМЕТИКА/ГИГИЕНА,5.62233,21.678079,1.89064,11.466001

In [26]:
res_2 = res[res["confidence(%)"] >= 5]
res_2

,Пара,support(%),confidence(%),lift,expected confidence(%)
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,1.968909,16.093405,0.526784,30.550265
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,2.483657,20.300831,1.770524,11.466001
6,ДЕТСКОЕ ПИТАНИЕ + ПОДГУЗНИКИ,4.770423,38.992321,1.503431,25.935554
8,"ДЕТСКОЕ ПИТАНИЕ + ТЕКСТИЛЬ, ТРИКОТАЖ",1.302311,10.644788,0.550576,19.333917
11,ДЕТСКОЕ ПИТАНИЕ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,2.128481,17.397707,1.548083,11.238225
...,...,...,...,...,...
146,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ИГРУШКИ,2.407732,21.424482,0.701286,30.550265
148,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КОСМЕТИКА/ГИГИЕНА,3.397334,30.230161,2.636504,11.466001
149,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КРУПНОГАБАРИТНЫЙ ТОВАР,1.308746,11.645483,0.597877,19.478046
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,3.706182,32.978358,1.271550,25.935554
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",2.185103,19.443490,1.005667,19.333917

In [33]:
res_2 = res_2.sort_values(['confidence(%)'], ascending = False)
res_2

,Пара,support(%),confidence(%),lift,expected confidence(%)
98,СОПУТСТВУЮЩИЕ ТОВАРЫ + ИГРУШКИ,0.298554,67.441860,2.207570,30.550265
15,ЖЕНСКИЕ ШТУЧКИ + КОСМЕТИКА/ГИГИЕНА,0.128687,52.910053,4.614517,11.466001
38,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ + ИГРУШКИ",2.098883,50.261941,1.645221,30.550265
124,ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА + КОСМЕТИКА/ГИГИЕНА,0.033459,50.000000,4.360718,11.466001
54,КОСМЕТИКА/ГИГИЕНА + ПОДГУЗНИКИ,5.622330,49.034792,1.890640,25.935554
...,...,...,...,...,...
101,СОПУТСТВУЮЩИЕ ТОВАРЫ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.027024,6.104651,0.313412,19.478046
143,ТОВАРЫ ДЛЯ ЖИВОТНЫХ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,0.106810,6.023222,0.535958,11.238225
76,ОБУВЬ + КОСМЕТИКА/ГИГИЕНА,0.356463,5.903666,0.514884,11.466001
51,"КОСМЕТИКА/ГИГИЕНА + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.620271,5.409652,1.295449,4.175889
89,ПОДГУЗНИКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,1.357647,5.234693,0.268748,19.478046

**Поставим поддержу >= 3%, чтобы было больше комбинаций**

In [35]:
res_3 = res_2[res_2["support(%)"] >= 3]
res_3

,Пара,support(%),confidence(%),lift,expected confidence(%)
54,КОСМЕТИКА/ГИГИЕНА + ПОДГУЗНИКИ,5.622330,49.034792,1.890640,25.935554
6,ДЕТСКОЕ ПИТАНИЕ + ПОДГУЗНИКИ,4.770423,38.992321,1.503431,25.935554
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,3.706182,32.978358,1.271550,25.935554
148,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КОСМЕТИКА/ГИГИЕНА,3.397334,30.230161,2.636504,11.466001
59,КОСМЕТИКА/ГИГИЕНА + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,3.397334,29.629630,2.636504,11.238225
88,ПОДГУЗНИКИ + КОСМЕТИКА/ГИГИЕНА,5.622330,21.678079,1.890640,11.466001
84,ПОДГУЗНИКИ + ДЕТСКОЕ ПИТАНИЕ,4.770423,18.393371,1.503431,12.234262
110,"ТЕКСТИЛЬ, ТРИКОТАЖ + ИГРУШКИ",3.492562,18.064430,0.591302,30.550265
95,ПОДГУЗНИКИ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,3.706182,14.289967,1.271550,11.238225
86,ПОДГУЗНИКИ + ИГРУШКИ,3.576208,13.788826,0.451349,30.550265
30,ИГРУШКИ + ПОДГУЗНИКИ,3.576208,11.705981,0.451349,25.935554
32,"ИГРУШКИ + ТЕКСТИЛЬ, ТРИКОТАЖ",3.492562,11.432182,0.591302,19.333917

**Сохраним таблицу**

In [37]:
res_3.to_csv('mba_sorted.csv', sep=";", encoding='cp1251') #save filtered dataframe

## <div align="center"> Продожление, вторая часть

### После консультации условия задачи были немного изменены, поэтому добавим некоторые части и посчитаем новые таблицы. Прошлые таблицы оставим, так как они всё равно могут понадобиться для аналитики. 

### Вначале добавим колонку с телефонами клиентов в таблицу с чеками

In [11]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

data = pd.read_csv("data_clean_market.csv", sep=";", encoding="cp1251") # open raw data file

In [38]:
clients = (data.loc[:, ["НомерЗаказаНаСайте", "Телефон_new"]]).to_numpy()

**Каждому чеку присвоим номер телефона клиента**

In [39]:
clients

array([['4513479_TR', '55574954-50515053535277'],
       ['4513502_TR', '55574954-56545048505170'],
       ['4513529_TR', '55575349-49505555535574'],
       ...,
       ['5031477_TR', '55574857-57485151544876'],
       ['5031783_TR', '55575450-53495456535575'],
       ['5031783_TR', '55575450-53495456535575']], dtype=object)

In [44]:
clients_dict = {a : b for a,b in clients}

**Достанем колонку с чеками из таблицы для MBA, переведём её в list. Создадим ещё один list, в котором будут номера клиентов, соответствующие чекам.**

In [53]:
mba = pd.read_csv('market_basket.csv', sep=";", encoding='cp1251')
mba

,Unnamed: 0,ЧЕК,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,0,1303000353_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
1,1,1303000358_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
2,2,1303000359_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
3,3,1303000360_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
4,4,1303000362_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77703,77703,5031766_TR,0,0,0,0,0,0,0,0,0,0,0,45,0
77704,77704,5031767_TR,0,0,1,0,0,0,0,0,0,0,0,0,0
77705,77705,5031782_TR,0,0,2,0,1,0,0,0,0,13,0,0,1
77706,77706,5031783_TR,6,0,0,0,0,0,0,2,0,0,0,0,0
77707,77707,5031784_TR,0,0,1,0,0,0,0,0,0,3,0,0,0

In [83]:
bills_mba = mba["ЧЕК"].values.tolist()
clients = []

In [84]:
for bill in bills_mba:
    clients.append(clients_dict[bill])

In [88]:
mba.insert(0, "ТЕЛЕФОН", clients, True)

In [93]:
mba = mba.drop(columns=["Unnamed: 0"])

**Получили таблицу для MBA по чекам, где каждому чеку соответствует номер клиента**

In [242]:
mba

,ТЕЛЕФОН,ЧЕК,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,55574956-54505252575473,1303000353_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
1,55574956-48545054565372,1303000358_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
2,55574956-54505754494877,1303000359_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
3,55575156-52505248485271,1303000360_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
4,55574956-57555048495073,1303000362_TR,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77703,55574953-51495455515770,5031766_TR,0,0,0,0,0,0,0,0,0,0,0,45,0
77704,55575349-54534851505672,5031767_TR,0,0,1,0,0,0,0,0,0,0,0,0,0
77705,55575053-49545552535673,5031782_TR,0,0,2,0,1,0,0,0,0,13,0,0,1
77706,55575450-53495456535575,5031783_TR,6,0,0,0,0,0,0,2,0,0,0,0,0
77707,55575448-49525553515370,5031784_TR,0,0,1,0,0,0,0,0,0,3,0,0,0

**Сделаем таблицу для MBA по клиентам**

In [117]:
mba_clients = mba.groupby(mba["ТЕЛЕФОН"]).sum()
mba_clients

,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
ТЕЛЕФОН,,,,,,,,,,,,,
55515349-57485148505273,0,0,0,0,0,1,0,0,0,0,0,0,0
55515349-57485748544876,0,0,0,0,0,1,0,0,0,0,0,0,0
55535057-57525455575274,0,0,0,0,0,0,0,0,0,3,0,0,0
55545651-57575053555375,0,0,0,0,0,0,1,0,0,0,0,0,0
55574848-48484957505771,0,0,8,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56574953-57535556534880,0,0,0,0,2,0,0,0,0,0,0,0,0
56575655-52525750505484,2,0,0,0,2,0,0,2,0,1,0,0,0
57485453-52545749545698,0,0,0,0,0,0,0,2,0,0,0,0,0
57485453-54565648545092,0,0,0,0,1,0,0,4,0,0,0,0,0
57545549-57544957525799,0,0,0,0,0,1,0,0,0,0,0,0,0

**Используя витрину после сегментации, разделим данные таблицы на 3 таблицы (столько сегментов), чтобы посчитать MBA для каждого сегмента отдельно**

Установим соответствие между телефонами клиентов и номерами сегментов, разобьём их на 3 списка.

In [187]:
segments = pd.read_csv('temp_cluster.csv', sep=",", encoding='cp1251')

*Так выглядит данная таблица*

In [190]:
segments.loc[:, ["phone", "cluster"]].head(10)

                     phone  cluster
0  55515349-57485748544876        0
1  55535057-57525455575274        1
2  55545651-57575053555375        1
3  55574848-48484957505771        2
4  55574848-48485049525576        0
5  55574848-48495057545270        1
6  55574848-48504852575373        1
7  55574848-48505151485270        1
8  55574848-48505157545677        0
9  55574848-48505654514877        1

In [191]:
segments = (segments.loc[:, ["phone", "cluster"]]).to_numpy()

In [143]:
segment0 = []
segment1 = []
segment2 = []
segments_dict = {a : b for a,b in segments}
for i in segments_dict:
    if segments_dict[i] == 0:
        segment0.append(i)
    elif segments_dict[i] == 1:
        segment1.append(i)
    elif segments_dict[i] == 2:
        segment2.append(i)

*Это таблицы по клиентам*

In [158]:
mba_clients0 = mba_clients[mba_clients.index.isin(segment0)]
mba_clients1 = mba_clients[mba_clients.index.isin(segment1)]
mba_clients2 = mba_clients[mba_clients.index.isin(segment2)]

*Это таблицы по чекам*

In [162]:
mba0 = mba[mba["ТЕЛЕФОН"].isin(segment0)]
mba1 = mba[mba["ТЕЛЕФОН"].isin(segment1)]
mba2 = mba[mba["ТЕЛЕФОН"].isin(segment2)]

*Создадим шесть итоговых таблиц: 3 по чекам и 3 по клиентам для сегментов*

In [167]:
params = ["support", "confidence", "lift", "expected confidence"]
rows = [' + '.join(i) for i in itertools.permutations(cols, 2)] #Список для названий строк
pairs = list(itertools.permutations(cols, 2)) #Список, с которым легко работать, чтобы считать показатели

In [342]:
res_bills0 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)
res_bills1 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)
res_bills2 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)
res_clients0 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)
res_clients1 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)
res_clients2 = pd.DataFrame(0.0, index=[i for i in rows], columns=params)

**Для подсчёта первой таблицы был выбран простой способ, но таблица считается долго из-за итерирования по строкам pandas dataframe. Поэтому в этот раз я решил оптимизировать прежние функии и использовать итерирование по спискам.**

In [343]:
def support(a, b, df):
    a = df[a].values.tolist()
    b = df[b].values.tolist()
    counter = 0
    for i in range(0, len(b)):
        if a[i] > 0 and b[i] > 0:
            counter += 1
    return counter/len(b)

In [344]:
def confidence(a, b, df):
    a = df[a].values.tolist()
    b = df[b].values.tolist()
    counter = 0
    total = 0
    for i in range(0, len(a)):
        if a[i] > 0:
            total += 1
            if b[i] > 0:
                counter += 1
    if total != 0:
        return counter/total
    else:
        return 0.0

In [345]:
def expconf(a, b, df):
    a = df[a].values.tolist()
    b = df[b].values.tolist()
    counter = 0
    for i in range(0, len(b)):
        if b[i] > 0:
            counter += 1
    return counter/len(b)

In [346]:
def compute_mba(result, mba, pairs):
    for i in range(0, len(pairs)):
        sup = support(pairs[i][0], pairs[i][1], mba)
        conf = confidence(pairs[i][0], pairs[i][1], mba)
        exconf = expconf(pairs[i][0], pairs[i][1], mba)
        if exconf != 0:
            lift = (conf / exconf)
        else: 
            lift = 0
        result['support'][i] = sup
        result['confidence'][i] = conf
        result['expected confidence'][i] = exconf
        result['lift'][i] = lift
    return result

**Теперь посчитаем все таблицы**

In [347]:
res_bills0 = compute_mba(res_bills0, mba0, pairs)
res_bills1 = compute_mba(res_bills1, mba1, pairs)
res_bills2 = compute_mba(res_bills2, mba2, pairs)
res_сlients0 = compute_mba(res_clients0, mba_clients0, pairs)
res_clients1 = compute_mba(res_clients1, mba_clients1, pairs)
res_clients2 = compute_mba(res_clients2, mba_clients2, pairs)

*Создадим функцию для перевода значений в проценты*

In [348]:
def percent_mba(res):
    for i in range(0, len(res)):
        res["support"][i] *= 100
        res["confidence"][i] *= 100
        res["expected confidence"][i] *= 100
    res.columns = ['support(%)', 'confidence(%)', 'lift', 'expected confidence(%)']
    return res

In [349]:
mba_clients_list = [res_clients0, res_clients1, res_clients2]
mba_bills_list = [res_bills0, res_bills1, res_bills2]

In [350]:
for df in mba_clients_list:
    df = percent_mba(df)
for df in mba_bills_list:
    df = percent_mba(df)

**Сохраним полученные таблицы**

In [351]:
res_clients0.to_csv('mba_clients0.csv', sep=";", encoding='cp1251')
res_clients1.to_csv('mba_clients1.csv', sep=";", encoding='cp1251')
res_clients2.to_csv('mba_clients2.csv', sep=";", encoding='cp1251')
res_bills0.to_csv('mba_bills0.csv', sep=";", encoding='cp1251')
res_bills1.to_csv('mba_bills1.csv', sep=";", encoding='cp1251')
res_bills2.to_csv('mba_bills2.csv', sep=";", encoding='cp1251')

*Откроем их, так как в будущем может потребоваться работа с ними. Сэкономим время на вычислениях*

In [352]:
res_clients0 = pd.read_csv("mba_clients0.csv", sep=";", encoding="cp1251")
res_clients1 = pd.read_csv("mba_clients1.csv", sep=";", encoding="cp1251")
res_clients2 = pd.read_csv("mba_clients2.csv", sep=";", encoding="cp1251")
res_bills0 = pd.read_csv("mba_bills0.csv", sep=";", encoding="cp1251")
res_bills1 = pd.read_csv("mba_bills1.csv", sep=";", encoding="cp1251")
res_bills2 = pd.read_csv("mba_bills2.csv", sep=";", encoding="cp1251")

In [361]:
res_bills0 = res_bills0.rename(columns={"Unnamed: 0": "Пара"})
res_bills1 = res_bills1.rename(columns={"Unnamed: 0": "Пара"})
res_bills2 = res_bills2.rename(columns={"Unnamed: 0": "Пара"})
res_clients0 = res_clients0.rename(columns={"Unnamed: 0": "Пара"})
res_clients1 = res_clients1.rename(columns={"Unnamed: 0": "Пара"})
res_clients2 = res_clients2.rename(columns={"Unnamed: 0": "Пара"})

## <div align="center"> Посмотрим таблицы, для каждой будут выставлены свои ограничения

**MBA по чекам для сегмента 0**

In [362]:
df = res_bills0[(res_bills0["support(%)"] >= 0.2) & (res_bills0["confidence(%)"] >= 5)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
113,"ТЕКСТИЛЬ, ТРИКОТАЖ + КРУПНОГАБАРИТНЫЙ ТОВАР",1.192735,70.967742,0.723938,98.03018
149,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.966838,66.459627,0.677951,98.03018
28,ИГРУШКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.939731,72.222222,0.736735,98.03018
52,КОСМЕТИКА/ГИГИЕНА + КРУПНОГАБАРИТНЫЙ ТОВАР,0.560224,79.487179,0.810844,98.03018
89,ПОДГУЗНИКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.551188,70.930233,0.723555,98.03018
77,ОБУВЬ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.307220,65.384615,0.666985,98.03018

**MBA по чекам для сегмента 1**

In [363]:
df = res_bills1[(res_bills1["support(%)"] >= 4.5) & (res_bills1["confidence(%)"] >= 5)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
54,КОСМЕТИКА/ГИГИЕНА + ПОДГУЗНИКИ,8.805148,51.018463,1.279196,39.883228
88,ПОДГУЗНИКИ + КОСМЕТИКА/ГИГИЕНА,8.805148,22.077320,1.279196,17.258748
6,ДЕТСКОЕ ПИТАНИЕ + ПОДГУЗНИКИ,7.557255,39.689052,0.995131,39.883228
84,ПОДГУЗНИКИ + ДЕТСКОЕ ПИТАНИЕ,7.557255,18.948454,0.995131,19.041158
95,ПОДГУЗНИКИ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,5.764566,14.453608,0.874661,16.524814
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,5.764566,34.884300,0.874661,39.883228
59,КОСМЕТИКА/ГИГИЕНА + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,5.310226,30.768314,1.861946,16.524814
148,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КОСМЕТИКА/ГИГИЕНА,5.310226,32.134859,1.861946,17.258748
30,ИГРУШКИ + ПОДГУЗНИКИ,4.711977,34.859316,0.874034,39.883228
86,ПОДГУЗНИКИ + ИГРУШКИ,4.711977,11.814433,0.874034,13.517125

**MBA по чекам для сегмента 2**

In [364]:
df = res_bills2[(res_bills2["support(%)"] >= 1) & (res_bills2["confidence(%)"] >= 5)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
38,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ + ИГРУШКИ",4.134022,93.350063,0.987028,94.576874
62,КРУПНОГАБАРИТНЫЙ ТОВАР + ИГРУШКИ,3.772851,69.641026,0.736343,94.576874
110,"ТЕКСТИЛЬ, ТРИКОТАЖ + ИГРУШКИ",3.206090,71.499380,0.755992,94.576874
86,ПОДГУЗНИКИ + ИГРУШКИ,2.678224,72.155689,0.762932,94.576874
146,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ИГРУШКИ,2.411513,81.273408,0.859337,94.576874
50,КОСМЕТИКА/ГИГИЕНА + ИГРУШКИ,2.111463,86.956522,0.919427,94.576874
74,ОБУВЬ + ИГРУШКИ,1.439129,71.153846,0.752339,94.576874

**MBA по клиентам для сегмента 0**

In [367]:
df = res_clients0[(res_clients0["support(%)"] >= 0.2) & (res_clients0["confidence(%)"] >= 5)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
113,"ТЕКСТИЛЬ, ТРИКОТАЖ + КРУПНОГАБАРИТНЫЙ ТОВАР",1.789556,100.000000,1.000000,100.000000
149,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КРУПНОГАБАРИТНЫЙ ТОВАР,1.545081,100.000000,1.000000,100.000000
28,ИГРУШКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,1.388617,100.000000,1.000000,100.000000
89,ПОДГУЗНИКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.821436,100.000000,1.000000,100.000000
52,КОСМЕТИКА/ГИГИЕНА + КРУПНОГАБАРИТНЫЙ ТОВАР,0.762762,100.000000,1.000000,100.000000
77,ОБУВЬ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.479171,100.000000,1.000000,100.000000
40,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ + КРУПНОГАБАРИТНЫЙ ТОВАР",0.283591,100.000000,1.000000,100.000000
119,"ТЕКСТИЛЬ, ТРИКОТАЖ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ",0.215138,12.021858,7.780729,1.545081
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0.215138,13.924051,7.780729,1.789556

**MBA по клиентам для сегмента 1**

In [374]:
df = res_clients1[(res_clients1["support(%)"] >= 7) & (res_clients1["confidence(%)"] >= 10)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
54,КОСМЕТИКА/ГИГИЕНА + ПОДГУЗНИКИ,11.950857,57.332402,1.324530,43.285103
88,ПОДГУЗНИКИ + КОСМЕТИКА/ГИГИЕНА,11.950857,27.609631,1.324530,20.844857
6,ДЕТСКОЕ ПИТАНИЕ + ПОДГУЗНИКИ,9.982823,49.366542,1.140497,43.285103
84,ПОДГУЗНИКИ + ДЕТСКОЕ ПИТАНИЕ,9.982823,23.062954,1.140497,20.221841
95,ПОДГУЗНИКИ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,8.978427,20.742534,0.992734,20.894349
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,8.978427,42.970601,0.992734,43.285103
30,ИГРУШКИ + ПОДГУЗНИКИ,8.040991,49.819625,1.150965,43.285103
86,ПОДГУЗНИКИ + ИГРУШКИ,8.040991,18.576809,1.150965,16.140208
59,КОСМЕТИКА/ГИГИЕНА + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,7.912894,37.960894,1.816802,20.894349
148,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + КОСМЕТИКА/ГИГИЕНА,7.912894,37.870977,1.816802,20.844857
32,"ИГРУШКИ + ТЕКСТИЛЬ, ТРИКОТАЖ",7.645055,47.366522,1.426561,33.203296
110,"ТЕКСТИЛЬ, ТРИКОТАЖ + ИГРУШКИ",7.645055,23.024989,1.426561,16.140208
92,"ПОДГУЗНИКИ + ТЕКСТИЛЬ, ТРИКОТАЖ",7.182160,16.592682,0.499730,33.203296
115,"ТЕКСТИЛЬ, ТРИКОТАЖ + ПОДГУЗНИКИ",7.182160,21.630864,0.499730,43.285103

**MBA по клиентам для сегмента 2**

In [379]:
df = res_clients2[(res_clients2["support(%)"] >= 2.8) & (res_clients2["confidence(%)"] >= 3)]
df.sort_values(['support(%)'], ascending = False)

,Пара,support(%),confidence(%),lift,expected confidence(%)
28,ИГРУШКИ + КРУПНОГАБАРИТНЫЙ ТОВАР,5.960992,5.960992,1.0,5.960992
62,КРУПНОГАБАРИТНЫЙ ТОВАР + ИГРУШКИ,5.960992,100.000000,1.0,100.000000
26,"ИГРУШКИ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",4.914751,4.914751,1.0,4.914751
38,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ + ИГРУШКИ",4.914751,100.000000,1.0,100.000000
32,"ИГРУШКИ + ТЕКСТИЛЬ, ТРИКОТАЖ",4.669336,4.669336,1.0,4.669336
110,"ТЕКСТИЛЬ, ТРИКОТАЖ + ИГРУШКИ",4.669336,100.000000,1.0,100.000000
30,ИГРУШКИ + ПОДГУЗНИКИ,3.648928,3.648928,1.0,3.648928
86,ПОДГУЗНИКИ + ИГРУШКИ,3.648928,100.000000,1.0,100.000000
35,ИГРУШКИ + ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,3.306639,3.306639,1.0,3.306639
146,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ИГРУШКИ,3.306639,100.000000,1.0,100.000000